name: Node.js Package

on:
  release:
    types: [released]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
          registry-url: https://npm.pkg.github.com/
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGE_TOKEN}}
